title: MyPCStatus
name: mypcstatus
email: support@mypcstat.us
description: the last status monitor for windows with love

baseurl: "/mypcstat.us"
url: ""

display_footer: inital  #change this to 'none' if you want to hide the footer copyright text

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

project_one: "CPU"
project_one_description: Realtime CPU usage
project_one_url: #
project_one_icon: location_on

project_two: Network
project_two_description: Send and Receive graph
project_two_url: #
project_two_icon: photo_camera


project_three: Memory
project_three_description: Memory usage
project_three_url: #
project_three_icon: hotel


project_four: Upcoming
project_four_description: a lot of feature is on the way
project_four_url: #
project_four_icon: restaurant

portfolio_heading: Features
portfolio_type: cards

syntax_highlighting: true
# Skill icons from https://konpa.github.io/devicon/

skills:
  - name: windows8
  - name: visualstudio
  - name: cplusplus
site:
  - colored: colored


icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Detail

github: https://github.com/mypcstat/mypcstat.us
medium: #
download: https://github.com/mypcstat/mypcstat.us/releases

baseurl: # if your site is located at /blog or /home, enter it here, otherwise leave it empty
url: http://localhost:4000/ #the url of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: UA-123057476-1

cookies_banner: show # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: Thanks!

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
